version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/types"
    versions:
    - 7.13.16
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.4
